---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.1
  name: nodedrains.k8s.gezb.co.uk
spec:
  group: k8s.gezb.co.uk
  names:
    kind: NodeDrain
    listKind: NodeDrainList
    plural: nodedrains
    singular: nodedrain
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Phase of the NodeDrain
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: Pods that are blocking drain
      jsonPath: .status.podsBlockingDrain
      name: Pods BlockingDrain
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: NodeDrain is the Schema for the nodedrains API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: NodeDrainSpec defines the desired state of NodeDrain.
            properties:
              nodeName:
                description: NodeName is the name of the node to drain
                type: string
              nodeRole:
                description: NodeRole is the nodes expected "role" label
                type: string
              numberOfNodes:
                description: NumberOfNodes is the expected number of nodes to be drained
                type: integer
              skipWaitForPodsToRestart:
                description: WaitForPods waits for the evicted pods to be running
                  again before completing
                type: boolean
              versionToDrainRegex:
                description: VersionToDrainRegex is a regex to match the expected
                  kubernetes version that we want to Drain
                type: string
            required:
            - nodeName
            - nodeRole
            - numberOfNodes
            - skipWaitForPodsToRestart
            - versionToDrainRegex
            type: object
          status:
            description: NodeDrainStatus defines the observed state of NodeDrain.
            properties:
              PendingEvictionPods:
                description: PendingEvictionPods is a list of pods still to be evicted
                items:
                  type: string
                type: array
              PodsToRestart:
                description: PodsToRestart is the list of pods that we are waiting
                  to restart
                items:
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
                type: array
              drainProgress:
                description: Percentage completion of draining the node
                type: integer
              evictionPods:
                description: EvictionPods is the total number of pods up for eviction
                  from the start
                type: integer
              lastError:
                description: LastError represents the latest error if any in the latest
                  reconciliation
                type: string
              lastUpdate:
                description: The last time the status has been updated
                format: date-time
                type: string
              nodeDrainCount:
                description: The number of NodeDrains discoverd
                type: integer
              phase:
                description: Phase represents the progress of this nodeDrain
                type: string
              podsBlockingDrain:
                description: PodsBlockingDrain is a list of pods that are blocking
                  the draining of this node
                type: string
              podsToBeEvicted:
                description: PodsToBeEvicted is the list of pods for the controller
                  needs to evict
                items:
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
                type: array
              totalPods:
                description: TotalPods is the total number of all pods on the node
                  from the start
                type: integer
            required:
            - evictionPods
            - nodeDrainCount
            - phase
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
